### ISSUE TITLE
Using Resources for the title

### ISSUE THREAD

**Issue by Anushiravani** [VahidN/DNTBreadCrumb.Core#1]
hi vahid thanks for this project
I have a project that is multilingual.
How can I use this project for multilingual

**Comment by VahidN** [comment]
- Added localization support via https://github.com/VahidN/DNTBreadCrumb.Core/commit/81c41175edc50157f3a318b94b8b79651cb9a702
- [Try V1.2](https://www.nuget.org/packages/DNTBreadCrumb.Core)
- How to use it:
   - [Setup localization](https://github.com/VahidN/DNTBreadCrumb.Core/blob/master/src/DNTBreadCrumb.Core.TestWebApp/Startup.cs#L20).
   - Add [new resource files](https://github.com/VahidN/DNTBreadCrumb.Core/tree/master/src/DNTBreadCrumb.Core.TestWebApp/Resources).
   - Use `TitleResourceName` & `TitleResourceType` [to specify](https://github.com/VahidN/DNTBreadCrumb.Core/blob/master/src/DNTBreadCrumb.Core.TestWebApp/Controllers/HomeController.cs#L39) the related key/value
