### ISSUE TITLE
Make this ia partial and include in the main theme

### ISSUE THREAD

**Issue by weedkiller** [VahidN/DNTBreadCrumb.Core#13]
hello, I like this, I was hoping to share a suggestion.

Right now it has to be added to every action, by default it would be nice to make it a partial thats part of the main theme and auto renders based on the controller/action path by default. So that the specific action-views dont have to worry about it.

thanks

**Comment by VahidN** [comment]
That `partial` is called a `tag helper` here:
```xml
<breadcrumb asp-homepage-title="Home"
             asp-homepage-url="@Url.Action("Index", "Home", values: new { area = "" })"
             asp-bootstrap-version="V3"
             asp-homepage-glyphicon="glyphicon glyphicon-home"></breadcrumb>
```
And those attributes are feeding this tag helper or partial to render different pieces of the breadcrumb.
[More info](https://github.com/VahidN/DNTBreadCrumb.Core/blob/master/README.md)
