### ISSUE TITLE
Previous item link

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTBreadCrumb.Core#15]
<div dir="rtl">
چه طوری میشه در صفحه create به صفحه قبل مه Index هست لینک بشه

![Screenshot_2019-11-29 پنل مدیریت آراد کنسرت](https://user-images.githubusercontent.com/49598914/69880526-6170a280-12df-11ea-9543-15b9084c8c13.png)

یعنی ایتم سالن در این صفحه باید فعال باشد و به صفحه index لینک شود؟

**Comment by VahidN** [comment]
You can use [multiple AddBreadCrumb](https://github.com/VahidN/DNTBreadCrumb.Core/blob/master/src/DNTBreadCrumb.Core.TestWebApp/Controllers/HomeController.cs#L23) methods and change their order using the `Order` property.
