### ISSUE TITLE
عدم تغییر مسیر در صفحات ajax

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/DNTBreadCrumb.Core#17]
<div dir="rtl">

سلام جناب نصیری

من صفحاتی دارم که به صورت Ajax داخل layout بارگذاری میشه. به چه صورتی میشه ساختار مسیریابی تغییر کنه؟
در همه Action ها ساختار زیر وجود دارد.
`[BreadCrumb(Title = "Home", UseDefaultRouteUrl = true, Order = 0)]`

**Comment by VahidN** [comment]
<div dir="rtl">

چرخه‌ي طول عمر يك صفحه چه در حالت معمولي و چه در حالت اي‌جكسي يكي هست. بنابراين اگر tag-helper آن در قسمت مناسبي در صفحه‌ي شما قرار گيرد كه جزئي از رندر شدن آن صفحه باشد، رندر خواهد شد

**Comment by rbsdotnet** [comment]
<div dir="rtl">
این taghelper در layout قرادارد و در هر صفحه قرار ندارد.

![Screenshot_2020-03-28 مدیریت موسسه](https://user-images.githubusercontent.com/49598914/77814827-533a6380-70d2-11ea-8b9e-267954bb05d2.png)

چون layout فقط یکبار بارگذاری می شود
باتوجه به صحبت شما باید این بخش رو در هرصفحه بگذارم درست؟

**Comment by VahidN** [comment]
بله. بايد جائي قرار گيرد كه جزئي از چرخه‌ي رندر آن قسمت باشد

**Comment by rbsdotnet** [comment]
<div dir="rtl">
@VahidN 

جناب نصیری
توی هر صفحه گذاشتم اما وقتی رندر میکنم کار نمیکنه یعنی از attribute نمیخونه
ولی وقتی به صورت دستی مسیر رو  اضافه میکنم کار میکنه 

`this.AddBreadCrumb(new BreadCrumb
            {
                Title = "Bank"
            });`

**Comment by rbsdotnet** [comment]
<div dir="rtl">
با بررسی کد های شما با تغییر خصوصویت IgnoreAjaxRequests به false مشکل برطرف شد
