### ISSUE TITLE
title comming from variable

### ISSUE THREAD

**Issue by fredjeantheodore** [VahidN/DNTBreadCrumb.Core#18]
# Summary of the issue
Is it   way to fill a title in a Action Link by a variable (or resx) instead of a const

// now
 [BreadCrumb(Title = "**Main index"**, Order = 1, IgnoreAjaxRequests = true)]
   public ActionResult Index()

// i would like
var varTitle= "My variable title comming from resx";
 [BreadCrumb(Title = **varTitle**, Order = 1, IgnoreAjaxRequests = true)]
   public ActionResult Index()

How can i do that ?

**Comment by VahidN** [comment]
[You can't. It's against the C# rules.](https://stackoverflow.com/questions/2827799/using-variables-within-attributes-in-c-sharp)
