### ISSUE TITLE
Areas / Features Support?

### ISSUE THREAD

**Issue by dotnetshadow** [VahidN/DNTBreadCrumb.Core#2]
Great library, 

I'm currently having problems using this with Areas or Attribute Routing including supporting Features support as shown here

https://msdn.microsoft.com/en-us/magazine/mt763233.aspx

Also I get an exception when applying 
UseDefaultRouteUrl()

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The default route of this controller not found.

DNTBreadCrumb.Core.BreadCrumbAttribute.getDefaultControllerActionUrl(ActionExecutingContext filterContext)
```

```
    [Area("Admin")]
    [Route("[area]/[controller]/")]
    [BreadCrumb(UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("DisplayName Controller")]
```

I think the real issue here is attribute routing?

**Comment by VahidN** [comment]
[I've completed the sample to show how to work with Areas](https://github.com/VahidN/DNTBreadCrumb.Core/commit/08681abce8851df71a1db9b2d3b9852181aaef1b). Make sure you have defined [the areas routing definitions](https://github.com/VahidN/DNTBreadCrumb.Core/blob/master/src/DNTBreadCrumb.Core.TestWebApp/Startup.cs#L66). Also [some links](https://github.com/VahidN/DNTBreadCrumb.Core/commit/b011a9ef362d3a1c48150a046121f39801dc1983) should be corrected too.

**Comment by dotnetshadow** [comment]
@VahidN Thank you so much appreciate it

**Comment by dotnetshadow** [comment]
@VahidN Just a follow up on what you did, I actually tried doing something similar but I couldn't get it working for my particular case. I'm using features folders etc so maybe it's tripping up on that, just thought you should know in case other people are using features folders.

In particular I'm using the a solution very similar to this:
https://github.com/ardalis/OrganizingAspNetCore

**Comment by VahidN** [comment]
I added a new sample called [TestWebApp.WithFeatureFolders](https://github.com/VahidN/DNTBreadCrumb.Core/tree/master/src/DNTBreadCrumb.Core.TestWebApp.WithFeatureFolders) based on the [Ardalis](https://github.com/ardalis/OrganizingAspNetCore) sample.

**Comment by dotnetshadow** [comment]
@VahidN Thank you so much that is awesome I'll give it a try later on
