### ISSUE TITLE
attribute breadcrumb not working for http Post form submit

### ISSUE THREAD

**Issue by stprasath** [VahidN/DNTBreadCrumb.Core#3]
Attribute breadcrumb not working for http Post form submit  and loosing all breadcrumb.

**Comment by VahidN** [comment]
> This behavior occurs because the GDI+ component of the .NET Framework does not have an encoder that you can use to save files as .wmf or .emf files.
https://msdn.microsoft.com/en-us/library/ktx83wah.aspx

**Comment by VahidN** [comment]
Fixed via https://github.com/VahidN/DNTBreadCrumb.Core/commit/82018c143c8860fd9cd2b087b533c1dea7b5fda2 . Update its nuget package.

**Comment by stprasath** [comment]
Great!!! Its working now for POST method of form submit. Thanks
