### ISSUE TITLE
Keeping Breadcrumb values instead of clearing it in every controller

### ISSUE THREAD

**Issue by duygukokcu** [VahidN/DNTBreadCrumb.Core#4]
Hi,
Thanks for the project, it is a great library!

My issue is, I am trying to navigate from one controller to another controller's action and I want to show the breadcrumb as 

> Controller1> Action1 > Action2

or

>  Controller1> Action1 >Controller2 > Action2

Action1 belongs to Controller1 and Action2 belongs to Controller2. Is there a way to provide this output with this library? I tried `ClearStack=false` to provide previous pages breadcrumb but it didn't work. 

Thanks

**Comment by VahidN** [comment]
This library won't save anything in the cache or session. It's designed to be lightweight. It uses `HttpContext.Items` for the storage and it will be cleared automatically at the end of the request.
You can use [AddBreadCrumb](https://github.com/VahidN/DNTBreadCrumb.Core/blob/master/src/DNTBreadCrumb.Core.TestWebApp/Controllers/HomeController.cs#L23) extension method to create multi level custom breadcrumbs.
